### ISSUE TITLE
Access Denied to download fontnik node-v47-win32-x64.tar.gz

### ISSUE THREAD

**Issue by jingsam** [mapbox/node-fontnik#111]
I'm trying to install node-fontnik on windows 10, but failed to download this:
https://mapbox-node-binary.s3.amazonaws.com/fontnik/v0.4.4/node-v47-win32-x64.tar.gz
Could you fix that, many thanks!

**Comment by mikemorris** [comment]
Welp, this error is because this project doesn't currently support Windows, so we're unable to build Node.js v5.x binaries for Windows. A pull request adding Windows support would be welcome and should be possible as [Windows binaries of FreeType are available](https://www.freetype.org/download.html).

**Comment by xingdavis** [comment]
@mikemorris I got the same issue on ubuntu14

sudo npm install -g fontnik

/usr/local/bin/build-glyphs -> /usr/local/lib/node_modules/fontnik/bin/build-glyphs
/usr/local/bin/font-inspect -> /usr/local/lib/node_modules/fontnik/bin/font-inspect

> fontnik@0.4.4 install /usr/local/lib/node_modules/fontnik
> node-pre-gyp install --fallback-to-build=false || (source ./scripts/install_mason.sh && node-pre-gyp install --build-from-source)

node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/fontnik/v0.4.4/node-v48-linux-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/fontnik/node_modules/node-pre-gyp/lib/install.js:101:37)
node-pre-gyp ERR! stack     at emitOne (events.js:101:20)
node-pre-gyp ERR! stack     at Request.emit (events.js:188:7)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/fontnik/node_modules/node-pre-gyp/node_modules/request/request.js:951:10)
node-pre-gyp ERR! stack     at emitOne (events.js:96:13)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:188:7)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:472:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:361:20)
node-pre-gyp ERR! stack     at emitOne (events.js:96:13)
node-pre-gyp ERR! System Linux 4.4.0-31-generic
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/fontnik/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/fontnik
node-pre-gyp ERR! node -v v6.7.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.19
node-pre-gyp ERR! not ok
403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/fontnik/v0.4.4/node-v48-linux-x64.tar.gz
sh: 1: source: not found

**Comment by mikemorris** [comment]
`node-v48-linux` in the error string indicates a Node.js ABI version we aren't currently building binaries for (Node 6?)

**Comment by jingsam** [comment]
@xingdavis Try to use node 4 or 5 to install node-fontnik. And do not forget to use VPN if you are in China.
Note that node 6 LTS has released. @mikemorris Can you have a consideration to provide v6 binary?

**Comment by xingdavis** [comment]
thanks @mikemorris @jingsam

**Comment by aguiraf** [comment]
Hi @mikemorris,  I keep getting the same issue on ubuntu14 also after #115 
`403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/fontnik/v0.4.4/node-v48-linux-x64.tar.gz`
Is this binary available in your amazon server? thanks.

**Comment by jingsam** [comment]
@aguiraf `node-v48-linux-x64.tar.gz` is for node 6, which currently is not provided by node-fontnik.

**Comment by mikemorris** [comment]
@aguiraf @jingsam @xingdavis I just published [v0.4.5](https://github.com/mapbox/node-fontnik/releases/tag/v0.4.5) with Node.js v6.x binaries!

**Comment by jingsam** [comment]
Awesome!

**Comment by aguiraf** [comment]
thank you very much!
