### ISSUE TITLE
How to set fallback in fontstack

### ISSUE THREAD

**Issue by mtfurlan** [mapbox/node-fontnik#113]
I would like to generate the fonstack "Open Sans Regular,Arial Unicode MS Regular"
I understand this means to use Open Sans, and fall back to Arial Unicode if necessary.

I do not understand how to call build-glyphs with a fallback option.

The example is just `build-glyphs "Open Sans Regular" glyphs/`, (which doesn't even work, I needed to actually specify the ttf file, `./bin/build-glyphs fonts/open-sans/OpenSans-Regular.ttf glyphs/`) which will just do one font, no fallback.

Looking at build-glyphs, the argument fs.readFileSync, takes a file and returns a buffer, which gets passed into the Range function defined in src/glyphs.cpp
I gave up tracking where it goes after that, but it's just a buffer. I don't see how this could get passed more than one file.

So are you just supposed to run something like

```
mkdir Open\ Sans\ Regular\,Arial\ Unicode\ MS\ Regular/
./bin/build-glyphs fonts/arial-unicode-ms/arial-unicode-ms.ttf Open\ Sans\ Regular\,Arial\ Unicode\ MS\ Regular/
./bin/build-glyphs fonts/open-sans/OpenSans-Regular.ttf Open\ Sans\ Regular\,Arial\ Unicode\ MS\ Regular/
```
Seems like that would overwrite the files, but I don't know what the format of those are, so the fallback might just be to load a different file.

Many thanks for any help

**Comment by lbud** [comment]
Hey @mtfurlan, at this time you can't specify multiple fonts to node-fontnik, but it sounds like you may be interested in something like https://github.com/mapbox/glyph-pbf-composite which decodes multiple glyph PBFs, composites them and reencodes them for use in Mapbox GL. Feel free to open another ticket in the relevant repo if you still run into problems.
