### ISSUE TITLE
Access denied when downloading tarball

### ISSUE THREAD

**Issue by emacgillavry** [mapbox/node-fontnik#130]
Permissions seem to have changed for 

> https://mapbox-node-binary.s3.amazonaws.com/fontnik/v0.4.8/node-v47-linux-x64.tar.gz

**Comment by jingsam** [comment]
node-v47-linux-x64.tar.gz is for node v5. try to install with node v4 or v6

**Comment by springmeyer** [comment]
@jingsam - thanks, you are correct. We only provide binaries currently for node v0.10.x, v0.12.x, v4, and v6 per what versions we build for in https://github.com/mapbox/node-fontnik/blob/master/.travis.yml.

**Comment by emacgillavry** [comment]
Was on node v5 indeed. Have upgraded node 6.9.5 and works like a charm. Thanks for pointing me into the right direction.
