### ISSUE TITLE
Many CJKs could not be found.

### ISSUE THREAD

**Issue by huangyingjie** [mapbox/node-fontnik#136]
The pbf doesn't contain their message, Their charcode are：
````js
34382、27665、38738，and many..
````
The font is `Source Han Sans CN Normal Normal`.

**Comment by huangyingjie** [comment]
Could somebody reply this issue? @mikemorris @mikelmaron

**Comment by lbud** [comment]
Hi @huangyingjie, it's hard to debug your issue without your source file or example code. I've tried to replicate it by downloading Source Han Sans CN Normal from [here](https://github.com/adobe-fonts/source-han-sans/blob/release/SubsetOTF/CN/SourceHanSansCN-Normal.otf). Here's a quick test script I ran to try to debug this, based loosely on code from this module's [tests](https://github.com/mapbox/node-fontnik/blob/master/test/fontnik.test.js):

``` js
const fontnik = require('./index.js');
const Glyphs = require('./test/format/glyphs');
const Protobuf = require('pbf');
const fs = require('fs');

const font = fs.readFileSync('./SourceHanSansTC-Normal.otf');
const testing = [34382, 27665, 38738];

fontnik.load(font, (err, faces) => {
	if (err || !faces || !Array.isArray(faces) || !faces.length) {
		console.error('error: ', err || 'no faces returned by fontnik.load');
		process.exit(1);
	}

	const loaded = faces && faces[0];
	if (faces) {
		testing.forEach(codepoint => {
			console.log('codepoint ' + codepoint + ' location:', (loaded.points.indexOf(codepoint) || codepoint + ' not found'));
		});
	}
});

testing.forEach(codepoint => {
	fontnik.range({ font: font, start: codepoint - 1, end: codepoint + 1 }, (err, res) => {
		var result = new Glyphs(new Protobuf(new Uint8Array(res)));
		if (err || !res) {
			console.error('error: ', err);
			process.exit(1);
		}

		console.log(result.stacks['Source Han Sans TC Normal'].glyphs[codepoint] || 'no codepoint found for ' + codepoint);
	});
});
```
output:
```
{ id: 27665,
  bitmap: <Buffer 38 4f 60 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 69 65 57 43 2a 0f 4a 65 7c 88 89 89 89 89 89 89 89 89 89 89 89 89 89 89 89 89 89 83 70 56 ... >,
  width: 20,
  height: 21,
  left: 3,
  top: -9,
  advance: 24 }
{ id: 34382,
  bitmap: <Buffer 00 00 00 00 00 00 00 15 30 4a 5f 6d 70 70 6d 60 4b 32 32 32 32 32 32 2b 1e 0c 00 00 00 00 00 00 00 00 02 21 3f 5c 77 8b 90 90 8b 78 5e 52 52 52 52 52 ... >,
  width: 22,
  height: 22,
  left: 1,
  top: -8,
  advance: 24 }
{ id: 38738,
  bitmap: <Buffer 11 24 33 3b 3c 3c 3c 3c 3c 4c 61 6f 71 71 6e 60 4a 3c 3c 3c 3c 3c 3c 36 29 17 28 3e 50 5a 5c 5c 5c 5c 5c 5f 79 8d 91 91 8c 77 5d 5c 5c 5c 5c 5c 5c 54 ... >,
  width: 20,
  height: 22,
  left: 2,
  top: -8,
  advance: 24 }
codepoint 34382 location: 23719
codepoint 27665 location: 17002
codepoint 38738 location: 28075
```

If you can provide more info on your source file/usage we might be able to help here.

**Comment by huangyingjie** [comment]
Hi, @lbud，These codepoints appear after using your `.otf` file.  I used a '.ttf' [file](http://s3.meituan.net/v1/mss_2337f9d8e6254e1dbf8bb9fd36629530/font/SourceHanSansCN/SourceHanSansCN-Normal.ttf) .
May be the `ttf` fonts has lost these codepoints.
My usage is:
````js
./node_modules/.bin/build-glyphs SourceHanSansCN-Normal.otf "./public"
````

**Comment by lbud** [comment]
Thanks @huangyingjie — that download helped. I verified that the ttf file contained at that download link is missing the codepoints you mentioned (34382, 27665, 38738). Also of interest is that it's missing the space character and that its body height is _much_ higher than that of the .otf file. For reference, here's a small test file I put together:
![screen shot 2017-05-12 at 11 18 13 am](https://cloud.githubusercontent.com/assets/3170312/26011349/96cdab0c-3705-11e7-805a-b91ac0bd4da9.png)
In this screenshot I have the .otf file enabled, and all characters (both Latin and Chinese) are Source Han Sans CN Normal.

![screen shot 2017-05-12 at 11 19 04 am](https://cloud.githubusercontent.com/assets/3170312/26011397/c8048af6-3705-11e7-9a72-fe68aea35b11.png)
In this screenshot I've disabled the .otf file and enabled the .ttf file. Moving my cursor through the file I can see that:
* all Latin characters are Source Hans CN Normal, although the space characters are now my fallback system font (Lucida),
* the body height is at least twice as high (I didn't manually change any spacing),
* the three Chinese characters in question have fallen back to my system fallback Chinese font, PingFang SC, but the two at the bottom (expected to work) are indeed Source Han CN Normal.

This is not a node-fontnik issue but rather a discrepancy between the Adobe-provided .otf version and the .ttf version (not sure of the source, but based on preliminary research it looks like Adobe only provides .otf so someone must have converted this font manually).

(For reference, `fontnik.load` returns 30603 codepoints for the .ttf file and 30790 codepoints for the .otf file — so you may find 187 missing codepoints in total, in addition to certain rendering discrepancies based on my body height observation.)

**Comment by lbud** [comment]
(As a partial explanation for the large body height, here's the metadata for, for example, codepoint 34381: there's a pretty drastic `top` discrepancy)
.otf:
```
{ id: 34381,
  width: 21,
  height: 22,
  left: 1,
  top: -8,
  advance: 24 }
```
.ttf:
```
{ id: 34381,
  width: 21,
  height: 22,
  left: 1,
  top: -23,
  advance: 24 }
```

**Comment by huangyingjie** [comment]
@lbud awesome！Thank you very much.

**Comment by JunYanchan** [comment]
@huangyingjie Can you tell me how to optimize CJK fonts?？ Thank you very much.
