### ISSUE TITLE
can not building from source on  win10 

### ISSUE THREAD

**Issue by tianbaolin** [mapbox/node-fontnik#140]
when I  built from source on  win10 ,I came across this fault:

PS D:\work\mallto\map\node_modules\.0.5.0@fontnik> npm install --build-from-source

> fontnik@0.5.0 install D:\work\mallto\map\node_modules\.0.5.0@fontnik
> node-pre-gyp install --fallback-to-build=true

In this solution, a project is generated at a time. To enable parallel generation, add the "/m" switch
  install_mason
  '.\install_mason.sh'  is not an internal or external command, nor is it a program that can run。
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: “cmd.exe” had exited. The code is 1。 [D:\work\mallto\map\node_modules\.0.5.0@fontnik\build\action_before_
build1.vc
xproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\work\mallto\map\node_modules\.3.6.2@node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\work\\mallto\\map\\node_modules\\.3.6.2@node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build=true" "--module=D:\\work\\mallto\\map\\node_mod
ules\\.0.5.0@fontnik\\lib\\binding\\fontnik.node" "--module_name=fontnik" "--module_path=D:\\work\\mallto\\map\\node_modules\\.0.5.0@fontnik\\lib\\binding"
gyp ERR! cwd D:\work\mallto\map\node_modules\.0.5.0@fontnik
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe D:\work\mallto\map\node_modules\.3.6.2@node-gyp\bin\node-gyp.js build --fallback-to-build=true --module=D:\work\mallto\ma
p\node_modules\.0.5.0@fontnik\lib\binding\fontnik.node --module_name=fontnik --module_path=D:\work\mallto\map\node_modules\.0.5.0@fontnik\lib\binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\work\mallto\map\node_modules\.0.5.0@fontnik\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 10.0.15063
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\work\\mallto\\map\\node_modules\\.0.5.0@fontnik\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build=true"
node-pre-gyp ERR! cwd D:\work\mallto\map\node_modules\.0.5.0@fontnik
node-pre-gyp ERR! node -v v6.9.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.33
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe D:\work\mallto\map\node_modules\.3.6.2@node-gyp\bin\node-gyp.js build --fallback-to-build=true --module=D:\work\mallto\map\node_modules\.0.5.0@fontnik\l
ib\binding\fontnik.node --module_name=fontnik --module_path=D:\work\mallto\map\node_modules\.0.5.0@fontnik\lib\binding' (1)

npm WARN fontnik@0.5.0 No license field.
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--build-from-source"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! fontnik@0.5.0 install: `node-pre-gyp install --fallback-to-build=true`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fontnik@0.5.0 install script 'node-pre-gyp install --fallback-to-build=true'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fontnik package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build=true
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fontnik
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fontnik
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\work\mallto\map\node_modules\.0.5.0@fontnik\npm-debug.log

I had installed node-pry-gyp and node-gyp。

**Comment by springmeyer** [comment]
Windows is not supported - https://github.com/mapbox/node-fontnik/issues/137
