### ISSUE TITLE
Forward port latest from node-cpp-skel

### ISSUE THREAD

**Issue by springmeyer** [mapbox/node-fontnik#142]
node-fontnik's build system is based off an early version of node-cpp-skel. We should forward port the latest goodies, which would unlock:

 - support for more node versions (https://github.com/mapbox/node-fontnik/issues/138)
 - moving the secure param's to the travis settings UI (no longer storing in .travis.yml) per https://github.com/mapbox/node-cpp-skel/blob/master/docs/publishing-binaries.md
 - ensuring the code is correctly formatted with clang-format and all bugs found by clang-tidy are fixed
 - mason-js is used (once that lands in node-cpp-skel)

/cc @GretaCB

**Comment by GretaCB** [comment]
PR over at https://github.com/mapbox/node-fontnik/pull/144

**Comment by springmeyer** [comment]
#144 is now wrapped up
