### ISSUE TITLE
README.md not up-to-date

### ISSUE THREAD

**Issue by mcm-jyl** [mapbox/node-fontnik#149]
> These dependencies can be installed manually by running ./scripts/install_mason.sh.

./scripts/install_deps.sh is correct.

**Comment by springmeyer** [comment]
Thanks for noticing. Would you be able to create a PR fixing this?

**Comment by andrewharvey** [comment]
this can be closed now

**Comment by springmeyer** [comment]
Thanks @andrewharvey
