### ISSUE TITLE
Port to NAN

### ISSUE THREAD

**Issue by mikemorris** [mapbox/node-fontnik#44]
Port to [NAN](https://github.com/rvagg/nan) to develop against both Node v0.10.x and v0.12.x. Some potentially helpful porting details at https://github.com/mapnik/node-mapnik/pull/256.

* [x] 0.8
* [x] 0.10
* [ ] 0.11

**Comment by springmeyer** [comment]
this happened as part of #80 in https://github.com/mapbox/node-fontnik/commit/6b62495f916d70806bb18d127ade25d9d8549cf8
