### ISSUE TITLE
C++ tests

### ISSUE THREAD

**Issue by mikemorris** [mapbox/node-fontnik#45]
The Node.js tests should move out with the Node.js bindings. Need to add some unit tests (using [Catch](https://github.com/philsquared/Catch/), [Boost.Test](http://www.boost.org/doc/libs/1_55_0/libs/test/doc/html/index.html) or [something else](https://en.wikipedia.org/wiki/List_of_unit_testing_frameworks#C.2B.2B)?) to actually test the core C++ library.

**Comment by springmeyer** [comment]
we now have 100% test coverage via javascript mocha tests in https://github.com/mapbox/node-fontnik/pull/80
