### ISSUE TITLE
Split out C++ library

### ISSUE THREAD

**Issue by mikemorris** [mapbox/node-fontnik#46]
From @springmeyer:

> It would be able to be installed into `/usr/local/`, for example, and would have a fontnik-config or a pkg-config entry so apps could find it.

> So one somewhat missing piece is how gyp would be used. Currently gyp is largely used when C++ code is vendored into another code base but it should work both ways, you should be able to have a set of gyp files that both allow for: 
- you to install a C++ lib into a given `--prefix`, and
- bundle/vendor it into a larger app and just point to its `.gyp` file

> If you strip node-gyp out you lose things that can be quickly added back. I think the best way to do it is a Python configure/install wrapper. We basically need cpp-gyp, written in Python, that works on Windows/Mac/Linux, and is able to take args like `--prefix`, `--debug`, `--enable-static`, `--enable-shared`, etc. Python dependency is already there due to gyp being Python.

**Comment by springmeyer** [comment]
closing as per https://github.com/mapbox/node-fontnik/pull/80#issuecomment-84055525
