### ISSUE TITLE
Default to a font with better coverage?

### ISSUE THREAD

**Issue by lbud** [mapbox/node-fontnik#75]
We discussed in chat that maybe [defaulting to Open Sans Regular](https://github.com/mapbox/node-fontnik/blob/0adad4d03afbc42b9e6ee2398b3425d891da7554/index.js#L14) might not be the most logical — should we change this to Arial Unicode MS Regular?

@mikemorris if this makes sense to you I'm happy to grab

**Comment by mikemorris** [comment]
Logic behind bundling Open Sans Regular in the git repo is that it's relatively small (doesn't add 20mb to the initial download) and licensed permissively, so it works well for running the tests. The actual code probably just shouldn't have a default at all.

**Comment by lbud** [comment]
Ah, makes sense. I'll grab this then and just remove the default.
