### ISSUE TITLE
Port packaging system to use mason

### ISSUE THREAD

**Issue by springmeyer** [mapbox/node-fontnik#84]
We should port the build/packaging system to use Mason for handling deps.

What this will unlock:

  - Easily pull in the latest versions of freetype, boost, and protobuf and have them be the same across osx + linux
  - No more source compiles needed like are currently done in https://github.com/mapbox/node-fontnik/tree/master/deps
  - being able to have the travis build use `sudo:false` for faster builds

Steps to port things:

  - [ ] delete `deps/build_boost.sh`, `deps/build_freetype.sh` and `deps/build_protobuf.sh`
  - [ ] inside `deps/travis_build.sh`:
   - [ ] install mason
   - [ ] replace the use of `ubuntu-toolchain-r` ppa with mason-provided C++11 toolchain: https://github.com/mapbox/mason/blob/master/scripts/setup_cpp11_toolchain.sh (so use clang++ instead of g++)
   - [ ] use mason to install and link all deps
   - [ ] set environment settings to point to linked deps dir `./mason_packages/.link` like `export  CXXFLAGS="$(pwd)/mason_packages/.link/include"` and `export LDFLAGS="$(pwd)/mason_packages/.link/lib"` and `export PKG_CONFIG_PATH="$(pwd)/mason_packages/.link/lib/pkgconfig"`

- [ ] back in `.travis.yml` do `source  ./deps/travis_build.sh` to run the script AND inherit the `CXXFLAGS` and `LDFLAGS` at https://github.com/mapbox/node-fontnik/blob/master/.travis.yml#L22
- [ ] try building the app and if it works confirm with `otool -L` (for OS X) and `ldd` (for linux) that `lib/fontnik.node` is not linking to any system `libprotobuf`, or `libfreetype`. If not dynamic linking is present them it means we've successfully statically linked to the mason-provided `.a` files in `./mason_packages/.link/lib/`

**Comment by mikemorris** [comment]
Yes please!
