### ISSUE TITLE
small values to `range()` gives odd results

### ISSUE THREAD

**Issue by mattdesl** [mapbox/node-fontnik#89]
I'm using `test/format/Glyph` to parse the font stacks and I'm running a test that looks like this:

```
fontnik.range({ font: font, start: 33, end: 40 }, cb)
```

The code points 33, 34, 35, etc are available in the font according to the `load()` function.

However, I never reach the `tag === 3` (from Glyphs#readGlyphs) while parsing data so it doesn't end up parsing any glyphs.

Using a larger range like 0-256, the code points 33, 34, 35 etc are able to be extracted.

**Comment by mikemorris** [comment]
I think the `baton->chars.emplace_back` for loop is [ending on the wrong value](https://github.com/mapbox/node-fontnik/blob/master/src/glyphs.cpp#L273). I'm guessing this should be `i <= baton->end` instead of `i <= array_size`?

**Comment by mattdesl** [comment]
yup, just tested. can submit PR - is there a specific dev branch to target?

**Comment by mikemorris** [comment]
Hah, we should really clean up some of those old branches. PR to `master` works! :+1:
