### ISSUE TITLE
a strange problem with range() method

### ISSUE THREAD

**Issue by VRCraze** [mapbox/node-fontnik#99]
First, great appreciation for your great work!

The range() method can't handle start and end parameters correctly. Here is the problem I encounted:

### Test1

- input: [start: 0, end: 64]
- result: 33 glyphs, glyph ids: [32, 64]. 

got the correct result.

![snip20151011_1](https://cloud.githubusercontent.com/assets/2696472/10414081/e0c22ab4-6ff4-11e5-8489-8ae4ddd5176d.png)

**Test2**

- input: [start: 1, end: 64]
- result: 32 glyphs, glyph ids: [32, 63]. 

The correct result should be 33 glyphs, glyph ids: [32, 64]. 

![snip20151011_2](https://cloud.githubusercontent.com/assets/2696472/10414096/3e2a9484-6ff5-11e5-96d1-0be11180cc09.png)

**Test3**

- input: [start: 32, end: 64]
- result: 1 glyphs, glyph ids: [32]. 

The correct result should be 33 glyphs, glyph ids: [32, 64]. 

![snip20151011_3](https://cloud.githubusercontent.com/assets/2696472/10414109/87209a30-6ff5-11e5-87d6-3d572a5a5754.png)

**Test4**

- input: [start: 33, end: 64]
- result: 0 glyphs, glyph ids: [ ]. 

The correct result should be 32 glyphs, glyph ids: [33, 64]. 

![snip20151011_4](https://cloud.githubusercontent.com/assets/2696472/10414111/a0c68170-6ff5-11e5-8864-f6a7bd2a8cad.png)

Here is the script I used to got the result, which is modified slightly from `bin/build-glyphs`

![snip20151011_5](https://cloud.githubusercontent.com/assets/2696472/10414119/388d0f2e-6ff6-11e5-91c3-35c9f9c9aaed.png)

I tested it in ubuntu 14.04 and Mac OS X 10.10.2, both are the same results. Wish someone could kindly give me some tip, Thanks!

**Comment by VRCraze** [comment]
This problem was caused by a bug in previous version and has already been fixed, see [https://github.com/mapbox/node-fontnik/issues/89](https://github.com/mapbox/node-fontnik/issues/89). Just make sure `lib/fontnik.node` is generated by current source code.

**Comment by mikemorris** [comment]
Oops, we never tagged a new release (and corresponding binary) including that fix, sorry @VRCraze! Will try to get something out today.

**Comment by mikemorris** [comment]
Tagged [`v0.3.3`](https://github.com/mapbox/node-fontnik/releases/tag/v0.3.3) and published a binary @VRCraze, that should fix it.

**Comment by mikemorris** [comment]
v0.3.3 had some issues with broken binary publishing. I unpublished it, fixed up the binary publishing, added Node.js v4.x support and just published v0.4.0 @VRCraze.
